#!/usr/bin/env bun
// Generates src/skill-content.ts from skill/ — the skill has to travel inside
// the single-file bundle (that is the whole point of `sentrinel skill`), and a
// bundler cannot read a directory at runtime.
//
//   bun run packages/mcp/scripts/gen-skill.ts
//
// skill/ is the source of truth. tests/skill.test.ts fails if the generated
// file drifts from it, so forgetting this step cannot ship.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath, not .pathname: a space in the checkout path arrives
// percent-encoded otherwise, and every read fails with ENOENT.
const PKG = fileURLToPath(new URL("..", import.meta.url));
const SRC = join(PKG, "skill");

export async function collect(dir: string = SRC): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const walk = async (d: string) => {
    for (const e of await readdir(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) await walk(p);
      else if (e.name.endsWith(".md")) files[relative(dir, p)] = await readFile(p, "utf8");
    }
  };
  await walk(dir);
  // SKILL.md first — it is the entry point, and both the printed form and the
  // written order should read that way.
  const rank = (p: string) => (p === "SKILL.md" ? "" : p);
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => rank(a).localeCompare(rank(b))));
}

export function render(files: Record<string, string>): string {
  return (
    "// Generated by scripts/gen-skill.ts from skill/. Do not edit — edit the\n" +
    "// markdown and re-run the generator; tests/skill.test.ts checks they agree.\n\n" +
    "export const SKILL_FILES: Record<string, string> = " +
    JSON.stringify(files, null, 2) +
    ";\n"
  );
}

if (import.meta.main) {
  const out = join(PKG, "src", "skill-content.ts");
  await writeFile(out, render(await collect()));
  console.log(`✓ skill-content.ts ← skill/ (${Object.keys(await collect()).length} files)`);
}
